=== Pallavijoshii/Zen_Training/Git/xmlrepo-master/telecomOrder/orderSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zensar.com/orderSchema" xmlns:tns="http://www.zensar.com/orderSchema" elementFormDefault="qualified">
<element name="orders">
	<complexType>
		<sequence>
			<element name="order" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="order-id">
							<simpleType>
								<restriction  base="string">
									<pattern value="OI-[0-9]{4}"></pattern>								
								</restriction>							
							</simpleType>						
						</element>
						<element name="Customer-Id">
							<simpleType>
								<restriction  base="string">
									<pattern value="C-[0-9]{6}"></pattern>								
								</restriction>							
							</simpleType>						
						</element>						
						<element name="Customer-Name" >
							<simpleType>
								<restriction  base="string">
									<pattern value="[a-zA-Z ]*" ></pattern>		
									<minLength value="10"></minLength>
									<maxLength value="20"></maxLength>						
								</restriction>							
							</simpleType>						
						</element>	
						<element name="Plan"  >
							<complexType>
								
								<attribute name="Plan" type="string"  use="required"></attribute>
															
							</complexType>						
						</element>				
						<element name="Service"  >
							<complexType>
								
								<attribute name="Service" type="string"  use="required"></attribute>
															
							</complexType>						
						</element>
						<element name="Billing-cycle">
							<simpleType>
								<restriction base="string">
									<enumeration value="monthly"></enumeration>
								<enumeration value="quarterly"></enumeration>
								<enumeration value="half-yearly"></enumeration>
								<enumeration value="yearly"></enumeration>
								</restriction>
							</simpleType>
						</element>
						<element name="Billing-Address" >
							<complexType>
							<attribute name="Billing-Address" type="string" use="optional"></attribute>
							
							</complexType>
						</element>
					<element name="Service-Address"  >
							<complexType>
								
								<attribute name="Service-Address" type="string"  use="required"></attribute>
															
							</complexType>						
						</element>	
						
					
					
					
					
					</sequence>
				
				
				
				
				</complexType>
			
			
			
			
			
			
			
			
			</element>
					







		
		
		
		
		
		</sequence>
	
	
	
	
	
	
	
	
	
	</complexType>










</element>




</schema>

=== Pallavijoshii/Zen_Training/xml/XmlXsdProject/xmlrepo-master/telecomOrder/src/orderDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:orders xmlns:tns="http://www.zensar.com/orderSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.zensar.com/orderSchema ../orderSchema.xsd ">
  <tns:order>
    <tns:order-id>OI-7956</tns:order-id>
    <tns:Customer-Id>C-549764</tns:Customer-Id>
    <tns:Customer-Name>Grishma Kagde</tns:Customer-Name>
    <tns:Plan Plan="Billing the customer"/>
    <tns:Service Service="Provide the details"/>
    <tns:Billing-cycle>monthly</tns:Billing-cycle>
    <tns:Billing-Address/>
    <tns:Service-Address Service-Address="Gulmohar colony, Pune"/>
  </tns:order>
</tns:orders>
